### ISSUE TITLE
Two lines plates

### ISSUE THREAD

**Issue by Covvperwood** [zjykzj/crnn-ctc#1]
Hi!

Do you think, modernozation of CRNN for two lines license plate is possible? (Added example)

Thank you for great job 👍
![License_plate_Poland_2006_two_lines](https://github.com/user-attachments/assets/e8595986-4b77-443f-a05e-1f0f76e0338a)

**Comment by zjykzj** [comment]
> Hi!
> 
> Do you think, modernozation of CRNN for two lines license plate is possible? (Added example)
> 
> Thank you for great job 👍 ![License_plate_Poland_2006_two_lines](https://private-user-images.githubusercontent.com/47600419/379811246-e8595986-4b77-443f-a05e-1f0f76e0338a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NDY4OTQsIm5iZiI6MTczMDU0NjU5NCwicGF0aCI6Ii80NzYwMDQxOS8zNzk4MTEyNDYtZTg1OTU5ODYtNGI3Ny00NDNmLWEwNWUtMWYwZjc2ZTAzMzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDExMjMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYzk2NDExNGQ4YzNlMjhlN2ZjMTM2ZTQyMTA4ZTM0Y2MyOTA2NTg5MzU3N2M0ZWIzZGNkYjI1NWE1ZDBmMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iWiMIS9hRHa10nSVVR6RavFms174O7R3bTYMTLBOdDs)

For fully standardized two line text, it is entirely possible to crop it in a fixed position, allowing for the stitching of a single line text image; For non-standard multi line text images, it involves not only text recognition but also text detection. You can refer to [zjykzj/LPDet](https://github.com/zjykzj/LPDet) to implement it.

**Comment by Covvperwood** [comment]
> > Hi!
> > Do you think, modernozation of CRNN for two lines license plate is possible? (Added example)
> > Thank you for great job 👍 ![License_plate_Poland_2006_two_lines](https://private-user-images.githubusercontent.com/47600419/379811246-e8595986-4b77-443f-a05e-1f0f76e0338a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NDY4OTQsIm5iZiI6MTczMDU0NjU5NCwicGF0aCI6Ii80NzYwMDQxOS8zNzk4MTEyNDYtZTg1OTU5ODYtNGI3Ny00NDNmLWEwNWUtMWYwZjc2ZTAzMzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDExMjMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYzk2NDExNGQ4YzNlMjhlN2ZjMTM2ZTQyMTA4ZTM0Y2MyOTA2NTg5MzU3N2M0ZWIzZGNkYjI1NWE1ZDBmMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iWiMIS9hRHa10nSVVR6RavFms174O7R3bTYMTLBOdDs)
> 
> For fully standardized two line text, it is entirely possible to crop it in a fixed position, allowing for the stitching of a single line text image; For non-standard multi line text images, it involves not only text recognition but also text detection. You can refer to [zjykzj/LPDet](https://github.com/zjykzj/LPDet) to implement it.

thank you!
